services:
  database:
    image: postgres:15
    environment:
      POSTGRES_DB: ${DB_NAME:-MSE}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-postgres}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - database
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DB_HOST=database

volumes:
  postgres_data:
